spring.application.name=cli-service
llm.api.base-url= https://api.groq.com/openai/v1/chat/completions
llm.api.key=${LLM_API_KEY}
llm.api.model=openai/gpt-oss-20b
spring.datasource.url=jdbc:postgresql://localhost:5432/troubleshooter
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect